name: expo CI

on :
  push :
    branches : [ develop, actions-github ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./app
        
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2
      
      - name: ğŸ— Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Config repo
        run: |
              cat ${{ secrets.GOOGLE_SERVICES }} > .google-services.json
              cat ${{ secrets.FIREBASE_CONFIG_DEV }} > ./src/config/authmiaajuda-firebase-dev.json
              cat ${{ secrets.FIREBASE_CONFIG }} > ./src/config/authmiaajuda-firebase.json
              cat ${{ secrets.ENV_VARIABLE }} > .env
        
      - name: ğŸ— Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}


      - name: ğŸ“¦ Install dependencies
        run: yarn install --pure-lockfile --non-interactive

      - name: ğŸš€ Publish app
        run: expo publish --release-channel staging --non-interactive
